name: bloc_architecture
description: The BLoC (Business Logic Components) is a design pattern that allows developers to separate the business logic and presentation layers of their Flutter app. This separation of concerns helps improve the overall structure and maintainability of the code. It eases the testing and scaling of the app over time.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  http:
  connectivity_plus:
  cupertino_icons:
  flutter_native_splash:
  flutter_launcher_icons:
  rxdart:
  auto_size_text:
  hive:
  path_provider:
  hive_flutter:
  dio:
  flutter_bloc:
  equatable: 
  url_launcher:
  toast:
dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #